{% set name = "diffpy.pdfmorph" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_pdfmorph/diffpy_pdfmorph-{{ version }}.tar.gz
  sha256: 2998fda4dc83685975f9ce20e57687ba3114f712987b49abcc1112b483a823f0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - pdfmorph = diffpy.pdfmorph.pdfmorphapp:main

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip
  run:
    - python >=3.10
    - matplotlib-base
    - diffpy.utils >=3.4.4
    - scipy
    - numpy
    - bg-mpl-stylesheets

test:
  imports:
    - diffpy.pdfmorph
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: http://github.com/diffpy/diffpy.pdfmorph
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'More quantitative measurements and analyses for spectra taken at different temperatures.'

  description: |
    PDFmorph is a Python software package designed to increase the insight
    researchers can get into their spectra collected for atomic pair 
    distribution functions
  doc_url: https://diffpy.github.io/diffpy.pdfmorph
  dev_url: https://github.com/diffpy/diffpy.pdfmorph

extra:
  recipe-maintainers:
    - Sparks29032
    - bobleesj
    - chiahaoliu
    - CJ-Wright
    - pavoljuhas
    - sbillinge
